### ISSUE TITLE
Adding route and Controller for "welcome" page in framework bundle recipe

### ISSUE THREAD

**Issue by petr-buchin** [symfony/recipes#52] opened 2017-05-03 19:45 UTC
I think DefaultController should be added for displaying "welcome page" after installation. 
At the moment if user follows [quick demo tutorial](https://medium.com/@fabpot/symfony-4-a-quick-demo-da7d32be323) by @fabpot, runs webserver and opens http://localhost:8000/ - he sees 404 Exception page.

**Comment by sstok** [comment] 2017-05-04 08:35
Related to https://github.com/symfony/flex/issues/20

**Comment by fabpot** [comment] 2017-06-11 00:06
Closing as a duplicate of symfony/flex#20

**Closed by fabpot** 2017-06-11 00:06 UTC
