### ISSUE TITLE
Updating doctrine/annotations deletes config/routes/annotations.yaml

### ISSUE THREAD

**Issue by Bilge** [symfony/recipes#1165] opened 2023-01-10 16:29 UTC
Updating `doctrine/annotations` deletes `config/routes/annotations.yaml` causing all annotation routes to fail.

```
Updating recipe for doctrine/annotations...


   Yes! Recipe updated!


  No files were changed as a result of the update.
```

Despite erroneously claiming no files were changed, it deletes `config/routes/annotations.yaml`.

>$ git status
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    config/routes/annotations.yaml
        modified:   symfony.lock
```

Unsurprisingly, this causes `Symfony\Component\HttpKernel\Exception\NotFoundHttpException` to be thrown by every page.

Occurs when updating the 1.0 recipe to 1.14.

According to https://github.com/symfony/recipes/issues/1076#issuecomment-1112637093, it should be the case that `symfony/routing` is pending an update, but it is not, according to the output of `composer symfony:recipes:update`, which does not list that recipe as requiring an update.

**Comment by stof** [comment] 2023-01-10 16:39
Duplicate of https://github.com/symfony/recipes/issues/1076

**Closed** 2023-01-10 17:15 UTC

**Comment by stof** [comment] 2023-01-11 08:42
Looking at the history, it looks like the routing recipe for 6.1+ is configuring the routing for attributes rather than for annotations.
